default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sso_client_development
  username: develop
  password: develop
  host: localhost

<% if ENV['CI'] %>
test:
  <<: *default
  database: sso_client_test_<%= ENV['BUILDKITE_JOB_ID'] %>
  username: test
  password: test
  host: localhost
<% else %>
test:
  <<: *default
  database: sso_client_test
  username: test
  password: test
  host: localhost
<% end %>

production:
  <<: *default
  database: rsrt
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
